Feature/ticket/sign/cmj
KBfinance-team-MetalWallet/metal-wallet-backend pull request #46
Opened 2024-10-05 16:48 UTC by veniharuka

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
* 기능 추가 상세 설명 필요시 작성하기
  
  - [x] 기능 추가
  - [ ] 기능 삭제
  - [ ] 버그 수정
  - [x] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
feature/ticket/sign/cmj-> dev

### 변경 사항

- FE에서 deviceId를 받으면 티켓 정보와 함께 티켓 정보를 암호화 하도록 수정.
- RSA서명 과정 오류로 BouncyCastle의 버전을 1.68로 다운그레이드
- 티켓의 무결성 및 사용가능 여부 기능 추가

### 검증 여부
- [x] postman으로 api 테스트 완료했습니다.

2024-10-06 01:22 UTC, heegane requested changes

2024-10-06 01:22 UTC, heegane commented on src/main/java/com/kb/wallet/ticket/dto/request/VerifyTicketRequest.java
> +  private SignedTicketResponse ticket;
클라이언트에서 해당 `SignedTicketResponse`를 어디에 저장하나요??

2024-10-06 01:22 UTC, heegane commented on src/main/java/com/kb/wallet/ticket/controller/TicketController.java
> +    Ticket ticket = ticketService.findTicketById(member.getId());
`ticketService`가서 확인해보니까
```java
@Override
  public Ticket findTicketById(Long id) {
    return ticketRepository.findById(id)
      .orElseThrow(() -> new CustomException(TICKET_NOT_FOUND_ERROR));
  }
```

이렇게 메서드가 작성되어 있고, 해당 메서드는 `ticketId`를 바탕으로 조회해서 `Ticket`객체를 반환하는 메서드인데
지금 컨트롤러에서는 `memberId`가 인자로 들어가고 있어요!

주 의도가 멤버가 가지고 있는 티켓 리스트를 조회하고 싶은거면 `List<Ticket>`으로 반환하는 `findTicketsByMemberId` 메서드를 하나 만들어야 할 것 같고,
이 티켓이 존재하는지 그리고 유효성 검사를 하고 싶다면 인자를 바꿔야 할 것 같네요!

2024-10-06 01:22 UTC, heegane commented on src/main/java/com/kb/wallet/ticket/controller/TicketController.java
> +    if (ticketService.isTicketAvailable(member.getId(), TicketResponse.toTicketResponse(ticket))) {
이거는 `memberId` 알맞게 잘 들어간 것 같네용

2024-10-07 05:59 UTC, veniharuka commented on src/main/java/com/kb/wallet/ticket/dto/request/VerifyTicketRequest.java
> +  private SignedTicketResponse ticket;
세션 스토리지에서 저장해야 했을 거라고 생각합니다.
하지만 현재 프로젝트 내에서는 verify과정을 생략했기에 문제 없을 것으로 보입니다!

2024-10-07 05:59 UTC, veniharuka commented on src/main/java/com/kb/wallet/ticket/controller/TicketController.java
> +    Ticket ticket = ticketService.findTicketById(member.getId());
해당 메서드는 불필요하다고 여겨져 삭제하였습니다!

2024-10-07 05:59 UTC, veniharuka commented on src/main/java/com/kb/wallet/ticket/controller/TicketController.java
> +    if (ticketService.isTicketAvailable(member.getId(), TicketResponse.toTicketResponse(ticket))) {
:)

2024-10-07 06:20 UTC, merged