Feature/ticket/test/cmj
KBfinance-team-MetalWallet/metal-wallet-backend pull request #63
Opened 2024-10-22 06:07 UTC by veniharuka

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
* 기능 추가 상세 설명 필요시 작성하기
  
  - [x] 기능 추가
  - [ ] 기능 삭제
  - [ ] 버그 수정
  - [x] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
ex) Feature/ticket/test/cmj -> dev

### 변경 사항

- Musical Domain / Repository / Service / Controller 에 대한 테스트 코드 작성

### 검증 여부
- [ ] postman으로 api 테스트 완료했습니다.

2024-10-23 12:53 UTC, heegane requested changes
지금 given, when, then이 어느 코드에는 있고, 어느 코드에는 없는데 통일 시켜주셨으면 좋겠습니다! (builder 패턴도)
어쩌다 보니 질문이 많아졌는데 잘 대답해주실 거라 믿습니다 ㅎㅎ 👍

2024-10-23 12:53 UTC, heegane commented on src/test/java/com/kb/wallet/musical/controller/MusicalControllerTest.java
> +  private Member member;
객체에 `@Mock`어노테이션 건 이유가 뭔가요??

2024-10-23 12:53 UTC, heegane commented on src/test/java/com/kb/wallet/musical/controller/MusicalControllerTest.java
> +  private Musical musical;
이 객체에는 `@Mock` 어노테이션이 왜 빠져있는건지 궁금합니다!

2024-10-23 12:53 UTC, heegane commented on src/test/java/com/kb/wallet/musical/controller/MusicalControllerTest.java
> +    MockitoAnnotations.openMocks(this);
이 코드 처음봐서 그런데 설명해 주실 수 있으신가용??

2024-10-23 12:53 UTC, heegane commented on src/test/java/com/kb/wallet/musical/domain/MusicalDomainTest.java
> +    musical = new Musical(
builder 씁시다!

2024-10-23 12:53 UTC, heegane commented on src/test/java/com/kb/wallet/musical/domain/MusicalDomainTest.java
> +          assertThat(m.getId()).isEqualTo(1L);  // 의도적으로 실패하도록 2L로 설정
주석 정리 부탁드립니다~!

2024-10-23 12:53 UTC, heegane commented on src/test/java/com/kb/wallet/musical/domain/MusicalDomainTest.java
> +        1L,
**필수 필드만으로 Musical 객체를 생성할 수 있다**를 검증하는거면 id도 null값으로 해도 되지 않을까요?! (auto increment 검증)

2024-10-23 12:53 UTC, heegane commented on src/test/java/com/kb/wallet/musical/service/MusicalServiceTest.java
> +  private MusicalServiceImpl musicalService;
`@InjectMock` 뺀 이유가 있을까요?!

2024-10-23 14:03 UTC, veniharuka commented on src/test/java/com/kb/wallet/musical/service/MusicalServiceTest.java
> +  private MusicalServiceImpl musicalService;
@InjectMocks의 잠재적 문제로는 
- 리플렉션을 사용하여 의존성을 주입하므로 런타임 시점까지 문제를 발견하지 못할 수 있음
- 의존성 주입 순서나 방식을 명확하게 제어하기 어려움
- 생성자가 여러 개인 경우 예상치 못한 동작이 발생할 수 있음
위 와 같은 잠재적 문제가 있기에 명시적인 의존성 주입을 진행한 것입니다.
또한 생성자 주입을 통해 테스트 코드만 봐도 의존성 구조를 파악 가능하고 나중에 의존성이 변경되더라도 컴파일 타임에 오류 발견 가능하다는 장점이 있습니다.

2024-10-23 14:03 UTC, veniharuka commented on src/test/java/com/kb/wallet/musical/domain/MusicalDomainTest.java
> +          assertThat(m.getId()).isEqualTo(1L);  // 의도적으로 실패하도록 2L로 설정
정리 했습니다!

2024-10-23 14:08 UTC, veniharuka commented on src/test/java/com/kb/wallet/musical/domain/MusicalDomainTest.java
> +    musical = new Musical(
@BeforeEach
void setUp() {
    startDate = LocalDate.builder()
        .year(2024)
        .month(1)
        .day(1)
        .build();
    endDate = LocalDate.builder()
        .year(2024)
        .month(12)
        .day(31)
        .build();
}
1. LocalDate.of()는 이미 충분히 명확하고 읽기 쉬움
2. 날짜 생성은 단순한 값 설정이므로 Builder가 제공하는 장점(유연성, 가독성)이 불필요
3. 오히려 Builder를 사용하면 코드가 더 길어지고 복잡해짐
4. LocalDate는 불변(immutable) 객체이며, of() 메서드로 충분히 안전한 객체 생성 가능 
Builder패턴은 주로 객체 생성이 목잡하고 선택적 매개변수가 많을 때 사용하는 경우로 알고 있는데위와 같은 이유가 있음에도 사용해야 하는 이유가 있나요?(진짜 모름)

2024-10-23 14:13 UTC, heegane commented on src/test/java/com/kb/wallet/musical/domain/MusicalDomainTest.java
> +    musical = new Musical(
보통 매개변수 4, 5개를 초과할 때 코드의 가독성과 유지보수를 위해서 Builder를 씁니다!
그리고 LocalDate.of()에서 Builder를 쓰자는게 아니라 **Musical**에서 쓰자는 의견이었어요! 현재는 생성자로 생성하고 있길래~
다른 테스트 코드에서는 Musical을 Builder패턴으로 생성해 둬서 통일이 되었음 하는 마음에 리뷰 달았습니다~

2024-10-23 14:24 UTC, veniharuka commented on src/test/java/com/kb/wallet/musical/domain/MusicalDomainTest.java
> +    musical = new Musical(
Musical 자체에 Builder 패턴을 사용하지 않는걸 확인했습니다! 
그리고 아실 수 있으시겠지만, LocalDate 자체는 Builder 패턴을 제공하지 않으며, 대신 정적 팩토리 메서드인 of()를 사용합니다. 
startDate = LocalDate.of(2024, 1, 1);   
endDate = LocalDate.of(2024, 12, 31); 
위와 같은 방법이 LocalDate를 생성하는 권장되는 방법이라고 하네요 !!
Builder형태로 만들고 싶다면 별도의 DateBuilder클래스를 만들어야 한다고합니다~

2024-10-23 14:34 UTC, heegane commented on src/test/java/com/kb/wallet/musical/domain/MusicalDomainTest.java
> +    musical = new Musical(
MusicalControllerTest에는
```java
musical = Musical.builder()
      .id(1L)
      .title("뮤지컬 제목")
      .ranking(1)
      .place("장소")
      .placeDetail("상세 장소")
      .ticketingStartDate(LocalDate.now())
      .ticketingEndDate(LocalDate.now().plusDays(30))
      .runningTime(120)
      .posterImageUrl("포스터 이미지 URL")
      .noticeImageUrl("공지 이미지 URL")
      .detailImageUrl("상세 이미지 URL")
      .placeImageUrl("장소 이미지 URL")
      .build();
  }
```
이렇게 작성되어 있는데 확인해 주실 수 있을까요?

2024-10-23 14:35 UTC, veniharuka commented on src/test/java/com/kb/wallet/musical/controller/MusicalControllerTest.java
> +  private Member member;
Member에 @Mock을 사용한 이유로는 
실제 동작이 필요없고 단순히 파라미터로만 전달되는 용도이고 ,
mocking된 객체의 특정 동작을 정의할 필요가 없으며,
null이 아닌 객체만 있으면 되기에 사용하였습니다!

2024-10-23 14:38 UTC, heegane commented on src/test/java/com/kb/wallet/musical/domain/MusicalDomainTest.java
> +    musical = new Musical(
20번부터 23번까지 고치자고 한게 아니라 23번 줄부터 확인해주셨음 했던거였어요...!
저는 23번만 클릭해서 리뷰 남겼는데 깃허브가 3줄 위까지 보여주더라구용 허허허

2024-10-23 14:40 UTC, veniharuka commented on src/test/java/com/kb/wallet/musical/domain/MusicalDomainTest.java
> +    musical = new Musical(
ㅋㅋㅋㅋㅋㅋ 확인해서 builder형태로 고쳤고, repository, controller에도 
말씀하신 builder처리 확인중입니다.
궁금한 점은 MusicalDomainTest에서의 id값을 auto increment를 검증하기 위해 null로 수정하였는데 이는 service, controller, repository에도 동일하게 null값으로 수정하면 될까요?

2024-10-23 14:42 UTC, heegane commented on src/test/java/com/kb/wallet/musical/domain/MusicalDomainTest.java
> +    musical = new Musical(
auto increment 사항은 Domain 관련 테스트이기 때문에 그 외의 레이어는 null값으로 수정안해도 될 것 같습니다~!

2024-10-27 10:32 UTC, seowonn reviewed
너무 많아서 아직 다 못봤는데 나중에 노션에 각 테스트(컨트롤러 테스트, 서비스 테스트, 도메인...)의 목적 및 특징 정리하면 좋을 것 같아요!

2024-10-27 10:32 UTC, seowonn commented on build.gradle
> +    testImplementation "org.assertj:assertj-core:${assertjVersion}"
흑 다들 build.gradle에 이거 넣은거죠? (내 블루스크린의 원흉..)
이거 통일된거면 누가 build.gradle만 dev에 push 좀여..

2024-10-27 10:32 UTC, seowonn commented on src/test/java/com/kb/wallet/musical/controller/MusicalControllerTest.java
> +    MockitoAnnotations.openMocks(this);
오.. 전 @ExtendWith(MockitoExtension.class) 이거 썼는데 이것도 통일해야 할까요?

2024-10-27 10:32 UTC, seowonn commented on src/test/java/com/kb/wallet/musical/domain/MusicalDomainTest.java
> +      Musical musicalWithRequiredFields = new Musical(
How about using Builder Pattern?

2024-10-27 11:47 UTC, chuseok reviewed
bb

2024-10-27 11:47 UTC, chuseok commented on src/test/java/com/kb/wallet/musical/controller/MusicalControllerTest.java
> +  private MusicalService musicalService;
저는 @Mock을 사용하면 service에 대한 Mockito 함수가 적용이 되는지 모르겠던데 잘 동작하나요?

2024-10-27 11:47 UTC, chuseok commented on src/test/java/com/kb/wallet/musical/domain/MusicalDomainTest.java
> +      assertThat(musicalWithRequiredFields)
이건 어떨 때 사용하는 검증인지 궁금해요

2024-10-27 11:47 UTC, chuseok commented on src/test/java/com/kb/wallet/musical/repository/MusicalRepositoryTest.java
> +    Page<Musical> page = new PageImpl<>(Arrays.asList(musical1, musical2));
repository 조회 테스트를 보통 이렇게 짜는건지 궁금합니다
객체 생성해서 repository에 대한 mocking 처리한게 아닌가 싶어서요

2024-10-27 11:47 UTC, chuseok commented on src/test/java/com/kb/wallet/musical/service/MusicalServiceTest.java
> +  private MusicalServiceImpl musicalServiceImpl;
@InjectMocks를 사용하지 않고 생성자를 호출해서 직접 객체를 생성한 이유가 궁금해요

2024-10-27 11:47 UTC, chuseok commented on src/test/java/com/kb/wallet/musical/service/MusicalServiceTest.java
> +      when(musicalRepository.findAllByRankingAsc(any(PageRequest.class))).thenReturn(musicals);
이 부분도 2개의 객체를 생성해서 return 해줬으니 당연히 Size가 2개인 거 같다는 느낌인 거 같은데 이렇게 짜는게 맞는지 궁금합니다

2024-11-13 14:01 UTC, merged